### ISSUE TITLE
nixd/Parser: trailing slash leads to infinite recursion in the parser

### ISSUE THREAD

**Issue by PgBiel** [nix-community/nixd#231]
Hi, thanks for the helpful project!
I was editing a `flake.nix` file in my currently WIP NixOS dotfiles repo, using VSCodium with the Nix IDE extension, having `nixd` as the chosen (and sole) language server, and it seems I hit some sort of memory leak condition, as the `nixd` process suddenly reached over 23 GB of memory usage, freezing my computer and forcing me to use Alt+SysRq+F (kernel OOM killer) to kill nixd and recover. I hope the info sent below can help diagnose the problem. I'll update this issue if this happens again.

**EDIT 1:** I can consistently reproduce the problem with the file set below. All I have to do is manually type out the line `vmnixos = import ./vm-base/nixos/configuration.nix` in the `flake.nix` file below, in VSCodium, and by the time I reach the end of the line, my memory is getting filled at the rate of several gigabytes per second. (`killall nixd` then restores my previously available memory.)

**EDIT 2:** I can also reproduce this issue (through the same steps above) by using `nixd` in `vim`, through the `coc.nvim` plugin (it's not specific to VSCodium).

**EDIT 3:** I found a minimal repro (below).

# Minimal Reproduction Steps

1. Create a folder with two Nix files, such as below:
```sh
mkdir -p /tmp/repro     
cd /tmp/repro                     
echo '[]' >> a.nix
touch b.nix  # optional
```

2. Edit `b.nix` (e.g. through `vim b.nix`), and manually type out the following (ensure you start with `{}` so it's recognized as an attribute set while you type):

```nix
{
    test = import ./././a.nix
}
```
3. Memory leak starts as you type out `././` (recursing into inner directories in the path seems to trigger the problem).

# System Info

- OS: OpenSUSE Tumbleweed, snapshot 20230708, x86_64
- Kernel version: 6.3.9
- Nixd version: 1.2.0 (installed through `nix-env -iA nixpkgs.nixd`)
- Nix IDE extension version: 0.2.1 (installed through VSCodium's marketplace)
- Vim version (if relevant to the second edit): 9.0 (2022 Jun 28)

# Relevant files

Those were the files I was using at the time of the problem, but the minimal repro above should be sufficient.

<details><summary><code>flake.nix</code> (top-level dir, no flake.lock)</summary>
<p>
(Note that I didn't finish typing it; I was editing (just typing in) the line beginning with <code>vmnixos</code> when this happened)

```nix
{
  description = "PgBiel's NixOS Configuration Flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.05";
  };

  outputs = {
    nixosConfigurations = {
      vmnixos = import ./vm-base/nixos/configuration.nix 
    }
  };
}
```
</p>
</details> 
<details><summary><code>./vm-base/nixos/configuration.nix</code></summary>
<p>

```nix
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running `nixos-help`).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "vmnixos"; # Define your hostname.
  # Pick only one of the below networking options.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.
  networking.networkmanager.enable = true;  # Easiest to use and most distros use this by default.

  # Set your time zone.
  time.timeZone = "America/Sao_Paulo";

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";
  # console = {
  #   font = "Lat2-Terminus16";
  #   keyMap = "us";
  #   useXkbConfig = true; # use xkbOptions in tty.
  # };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # use LightDM as display manager
  services.xserver.displayManager.lightdm.enable = true;

  # XFCE
  services.xserver.desktopManager = {
    xterm.enable = false;
    xfce.enable = true;
  };
  services.xserver.displayManager.defaultSession = "xfce";

  # Configure keymap in X11
  services.xserver.layout = "us";
  services.xserver.xkbModel = "pc104";
  services.xserver.xkbVariant = "alt-intl";
  services.xserver.xkbOptions = "eurosign:e,ctrl:nocaps";

  # Enable CUPS to print documents.
  # services.printing.enable = true;

  # Enable sound.
  # sound.enable = true;
  # hardware.pulseaudio.enable = true;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
  };

  # Enable touchpad support (enabled default in most desktopManager).
  # services.xserver.libinput.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.pgbiel = {
    isNormalUser = true;
    extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
    packages = with pkgs; [
      firefox
      tree
    ];
    initialPassword = "password";
  };

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    wget
    nnn
    git
    jdk17
  ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Flatpak
  services.flatpak.enable = true;

  # XDG Portals, for flatpak
  xdg.portal.enable = true;
  xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-gtk ];

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # Copy the NixOS configuration file and link it from the resulting system
  # (/run/current-system/configuration.nix). This is useful in case you
  # accidentally delete configuration.nix.
  system.copySystemConfiguration = true;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "23.05"; # Did you read the comment?

}
```
</p>
</details>

<details><summary><code>./vm-base/nixos/hardware-configuration.nix</code></summary>
<p>

```nix
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "virtio_pci" "xhci_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
    };

  fileSystems."/hostshare" =
    { device = "/hostshare";
      fsType = "virtiofs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/NIXSWAP"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
```

</p>
</details>

<details><summary><code>./vm-base/nixos/.nixd.json</code></summary>
<p>

(Not supposed to work fully; just the file I had at the time, which I took from this repo's examples)

```json
{
    "options": {
        "enable": true,
        "target": {
            "args": [
                "--expr",
                "(import <nixpkgs/nixos> { configuration = ./configuration.nix; }).options"
            ],
            "installable": ""
        }
    }
}
```

</p>
</details>
<details><summary>Nix IDE settings in <code>settings.json</code></summary>
<p>

```json
{
  /* ... */
  "nix.enableLanguageServer": true,
  "nix.serverPath": "nixd"
}
```
</p>
</details>

# Logs
Problem occurred after the 19:32 timestamp.
[1-Nix-log.log (828 kiB)](https://github.com/nix-community/nixd/files/12166327/1-Nix-log.log)

**Comment by inclyc** [comment]
This is a bug in the generated parser:

```
(gdb) bt
#0  0x0000555d0c1b526f in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data (this=0x7ffcb435c1f8)
    at /nix/store/6vwsydq4nzr1l8j7fyg5r61nknwq6w60-gcc-12.3.0/include/c++/12.3.0/bits/basic_string.h:234
#1  0x0000555d0c1c156b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[] (this=0x7ffcb435c1f8, __pos=1)
    at /nix/store/6vwsydq4nzr1l8j7fyg5r61nknwq6w60-gcc-12.3.0/include/c++/12.3.0/bits/basic_string.h:1210
#2  0x0000555d0c1c10db in boost::io::detail::upper_bound_from_fstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::ctype<char> > (buf=..., arg_mark=37 '%', 
    fac=..., exceptions=255 '\377') at include/boost/format/parsing.hpp:446
#3  0x0000555d0c1c056c in boost::basic_format<char, std::char_traits<char>, std::allocator<char> >::parse (this=0x7ffcb435c580, buf=...) at include/boost/format/parsing.hpp:484
#4  0x0000555d0c1c02bf in boost::basic_format<char, std::char_traits<char>, std::allocator<char> >::basic_format (this=0x7ffcb435c580, s=...) at include/boost/format/format_implementation.hpp:64
#5  0x0000555d0c1c01a1 in nix::hintformat::hintformat (this=0x7ffcb435c580, format=...)
    at /nix/store/a9k62aq1dnf57aak9yc89aldf2rnaxfr-nix-2.16.1-dev/include/nix/fmt.hh:94
#6  0x0000555d0c1c00fc in nix::hintfmt<nix::normaltxt<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (fs=..., args=...)
    at /nix/store/a9k62aq1dnf57aak9yc89aldf2rnaxfr-nix-2.16.1-dev/include/nix/fmt.hh:137
#7  0x0000555d0c1b2311 in nix::hintfmt (plain_string=...)
    at /nix/store/a9k62aq1dnf57aak9yc89aldf2rnaxfr-nix-2.16.1-dev/include/nix/fmt.hh:145
#8  0x0000555d0c1af120 in yylex (yylval_param=0x7ffcb435cbe0, yylloc_param=0x7ffcb435cbf8, 
    yyscanner=0x555d0c38ac10, data=0x555d0c2ea970) at ../nixd/lib/Parser/Lexer.l:205
#9  0x0000555d0c1ce082 in yygetToken (yycharp=0x7ffcb435cbdc, yystackp=0x7ffcb435caf8, 
    scanner=0x555d0c38ac10, data=0x555d0c2ea970) at nixd/lib/Parser/Parser.tab.cpp:1336
#10 0x0000555d0c1ccec0 in yyparse (scanner=0x555d0c38ac10, data=0x555d0c2ea970)
    at nixd/lib/Parser/Parser.tab.cpp:3572
#11 0x0000555d0c1cf67b in nixd::parse (text=0x555d0c3bee60 "{\n  oom = import ./././\n}", length=27, 
    origin=..., basePath=..., state=...) at ../nixd/include/nixd/Parser/Epilogue.cpp:41
#12 0x00007fe6acef488a in nixd::parse (Text=0x555d0c3bee60 "{\n  oom = import ./././\n}", Length=27, 
    Origin=..., BasePath=..., State=..., Env=...) at ../nixd/include/nixd/Parser/Parser.h:51
#13 0x00007fe6acef4757 in nixd::parse (Text=0x555d0c3bee60 "{\n  oom = import ./././\n}", Length=27, 
    Origin=..., BasePath=..., State=...) at ../nixd/include/nixd/Parser/Parser.h:62
#14 0x00007fe6acef3fd6 in nixd::parse (Text=..., Origin=..., BasePath=..., State=...)
    at ../nixd/include/nixd/Parser/Parser.h:81
#15 0x00007fe6acef3788 in nixd::EvalDraftStore::injectFiles (this=0x7ffcb435e768, State=...)
    at ../nixd/lib/Server/EvalDraftStore.cpp:31
#16 0x00007fe6acedbacf in nixd::Server::evalInstallable (this=0x7ffcb435e580)
    at ../nixd/lib/Server/Eval.cpp:58
#17 0x00007fe6acedb396 in nixd::Server::switchToEvaluator (this=0x7ffcb435e580)
    at ../nixd/lib/Server/Eval.cpp:43
#18 0x00007fe6ace1f158 in nixd::Server::updateWorkspaceVersion()::$_11::operator()() const (
    this=0x7ffcb435d990) at ../nixd/lib/Server/Controller.cpp:121
#19 0x00007fe6ace1f12d in llvm::detail::UniqueFunctionBase<void>::CallImpl<nixd::Server::updateWorkspaceVersion()::$_11>(void*) (CallableAddr=0x7ffcb435d990)
    at /nix/store/zwngfkcvzdbsig9k4kf9r22q0nbbyifa-llvm-16.0.1-dev/include/llvm/ADT/FunctionExtras.h:221
#20 0x00007fe6ace1f5df in llvm::unique_function<void ()>::operator()() (this=0x7ffcb435d990)
    at /nix/store/zwngfkcvzdbsig9k4kf9r22q0nbbyifa-llvm-16.0.1-dev/include/llvm/ADT/FunctionExtras.h:383
#21 0x00007fe6ace0bf96 in nixd::Server::forkWorker(llvm::unique_function<void ()>, std::deque<std::unique_ptr<nixd::Server::Proc, std::default_delete<nixd::Server::Proc> >, std::allocator<std::unique_ptr<nixd::Server::Proc, std::default_delete<nixd::Server::Proc> > > >&, unsigned long) (
```

And, the stack trace may indicate that it is not "leaking", instead it traps into a infinite parsing state that trying to acquire the memory.

**Comment by inclyc** [comment]
The minimum reproducer:

```nix
{
  oom = import ./././
}
```

This will lead to a infinite recursion in our extended parser.

```console
$ nixd-ast-dump issue-231.nix
// hangs here
```

**Comment by inclyc** [comment]
Can you checkout the corresponding branch in #232 to confirm it fixes this issue?

**Comment by inclyc** [comment]
Would you like to cherry-pick this patch on the release branch?

**Comment by PgBiel** [comment]
> Would you like to cherry-pick this patch on the release branch?

Up to you haha
Personally, I wouldn't mind it though (perhaps by releasing a v1.2.1 or something, if you feel that's appropriate)
